{"name": "test_forgot_password", "status": "broken", "statusDetails": {"message": "TypeError: find_element() takes from 1 to 3 positional arguments but 13 were given", "trace": "app = <application.Application object at 0x038E0150>\nmake_screen = <function make_screen at 0x0367D078>\n\n    @allure.feature('Forgot password')\n    def test_forgot_password(app, make_screen):\n        \"\"\" Testcase to renew password using email\"\"\"\n        app.header.click_icon()\n>       app.header.click_log_in()\n\ntest_forgot_password.py:14: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\pages\\header.py:31: in click_log_in\n    self.browser.click_element_by_text_simple(self.locators.LOG_IN)\n..\\driver_wrapper.py:53: in click_element_by_text_simple\n    WebDriverWait(self.driver, self.default_timeout).until(EC.element_to_be_clickable(locator_and_text[0]))\nC:\\Users\\Nataliya\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py:71: in until\n    value = method(self._driver)\nC:\\Users\\Nataliya\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py:297: in __call__\n    element = visibility_of_element_located(self.locator)(driver)\nC:\\Users\\Nataliya\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py:128: in __call__\n    return _element_if_visible(_find_element(driver, self.locator))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\ndriver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"ff9d0642879a61cd06f05612482995a8\")>\nby = 'css selector'\n\n    def _find_element(driver, by):\n        \"\"\"Looks up an element. Logs and re-raises ``WebDriverException``\n        if thrown.\"\"\"\n        try:\n>           return driver.find_element(*by)\nE           TypeError: find_element() takes from 1 to 3 positional arguments but 13 were given\n\nC:\\Users\\Nataliya\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py:411: TypeError"}, "description": " Testcase to renew password using email", "start": 1566416500253, "stop": 1566416500445, "uuid": "609d3f6c-d386-4cd3-a2d0-729ecd49aee3", "historyId": "f4a0a55e25094821a3cff22a672beb7e", "fullName": "tests.test_forgot_password#test_forgot_password", "labels": [{"name": "feature", "value": "Forgot password"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_forgot_password"}, {"name": "subSuite"}, {"name": "host", "value": "DESKTOP-Q2AH420"}, {"name": "thread", "value": "6428-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_forgot_password"}]}